basePath: /
definitions:
  CEP:
    properties:
      address:
        example: Rua Paula Rodrigues
        type: string
      city:
        example: Osasco
        type: string
      code:
        example: 06233-030
        type: string
      district:
        example: Piratininga
        type: string
      state:
        example: SP
        type: string
    type: object
  ERROR:
    properties:
      message:
        type: string
    type: object
host: localhost:8000
info:
  contact:
    email: martin.harano@fullcycle.com.br
    name: Martin Harano
    url: https://github.com/martin-harano
  description: API to demonstrate multithreading
  license:
    name: Martin Harano License
    url: https://github.com/martin-harano
  termsOfService: http://swagger.io/terms/
  title: Desafio2 - Multithread
  version: "1.0"
paths:
  /cep/{code}:
    get:
      consumes:
      - application/json
      description: Get a CEP
      parameters:
      - description: ZIP code (exact 8 number digits)
        in: path
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/CEP'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/ERROR'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ERROR'
        "504":
          description: No response from servers" example(test)
          schema:
            $ref: '#/definitions/ERROR'
      summary: Get a CEP
      tags:
      - CEP
swagger: "2.0"
